name: Lint test and build

# Controls when the workflow will run
'on':
  #triggers the workflow whenever a push is made to the main branch
  push:
    branches:
      - develop

jobs:
  #this workfloe has only one job
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run lint, test and build in frontend
        run: yarn --cwd frontend && yarn --cwd frontend lint && yarn --cwd frontend test && yarn --cwd frontend build
