name: Lint test and build

# Controls when the workflow will run
'on':
  #triggers the workflow whenever a push is made to the main branch
  push:
    branches:
      - develop

jobs:
  #this workfloe has only one job
  deploy_to_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # this install the dependencies specified in your package.json file into the current workflow
      - name: install dependencies
        # navigates to your functions folder and install the dependencies
        run: yarn && yarn lint && yarn test && yarn build
        # If your firebase cloud functions project uses firebase-admin 
        # you need to create a config file used to initialize your project
        # the below task creates a config.json file in your functions directory
