name: Update Function api_live
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    if: ${{ false }}
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: '14'
      - name: Build
        working-directory: backend
        run: yarn && yarn build
      - name: Deploy to Firebase
        uses: docker://w9jds/firebase-action:master
        with:
          args: deploy --only functions:api_live --debug
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}