name: Preview functions in firebase
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Lint Check
        run: yarn --cwd backend && yarn --cwd backend lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: yarn --cwd backend && yarn --cwd backend test
  
  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - name: E2E Test
        run: yarn --cwd backend && yarn --cwd backend test:e2e
  
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test, e2e-test]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn --cwd backend
      - name: Build
        run: yarn --cwd backend build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: backend/dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: backend/dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}