name: Preview functions in firebase
on:
  push:
    branches:
      - develop
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Lint Check
        working-directory: backend
        run: yarn && yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Test
        working-directory: backend
        run: yarn && yarn test
  
  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: E2E Test
        working-directory: backend
        run: yarn && yarn test:e2e
  
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test, e2e-test]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install Dependencies
        working-directory: backend
        run: yarn --cwd backend
      - name: Build
        working-directory: backend
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: backend/dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: backend/dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions:api_test
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}