name: Preview Hosting
on:
  pull_request:
    
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Lint Check
        working-directory: frontend
        run: yarn && yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Test
        working-directory: frontend
        run: yarn && yarn test

  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Test coverage
        working-directory: frontend
        run: yarn && yarn test:cov

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test, coverage]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Build
        working-directory: frontend
        run: yarn && yarn build:preview
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: frontend/dist
  