name: Preview in Firebase Hosting
on:
  push:
    branches:
      - develop
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Lint Check
        working-directory: frontend
        run: yarn && yarn lint
  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: yarn --cwd frontend && yarn --cwd frontend test
  
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn --cwd frontend
      - name: Build
        run: yarn --cwd frontend build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: frontend/dist
  
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: frontend/dist
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WSNE_28B5B }}'
          channelId: preview
          projectId: wsne-28b5b
