name: Deploy functions in firebase
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Build
        working-directory: backend
        run: yarn && yarn build
      - name: Deploy to Firebase
        uses: docker://w9jds/firebase-action:master
        with:
          args: deploy --only functions:api --debug
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}