name: Preview functions in firebase
on:
  push:
    branches:
      - develop
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Lint Check
        working-directory: backend
        run: yarn && yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Test
        working-directory: backend
        run: yarn && yarn test
  
  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: E2E Test
        working-directory: backend
        run: yarn && yarn test:e2e
  
  build_and_deploy:
    name: Deploy
    needs: [lint, test, e2e-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Build
        working-directory: backend
        run: yarn
      - name: Deploy to Firebase
        uses: docker://w9jds/firebase-action:master
        with:
          args: deploy --only functions:api_test --debug
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}